# Site settings
title: 易立思翻译
email: translate@elixirenglish.com
description: > # this means to ignore newlines until "baseurl:"
  易立思为您提供最优质的翻译服务！
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

ga_tracking_id: UA-78608624-5  # Google Analytics Tracking ID

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"
